# GPIO
BUTTON_PIN = 23
BUTTON_GREEN_LED = 4
YELLOW_DICE_LED = 27 # ORANGE
PINK_DICE_LED = 17   # WHITE
BLUE_DICE_LED = 22   

# Drucker
PRINTER_NAME = "Termo"
PRINTER_WIDTH = 32 # Zeichen für 58mm Thermodrucker